# Exported from Render on 2024-12-31T00:01:42Z
services:
- type: web
  name: Signal-Copier-Telegram-Bot
  runtime: python
  repo: https://github.com/carsti/Signal-Copier-Telegram-Bot/
  plan: free
  envVars:
  - key: RISK_FACTOR
    sync: true
  - key: ACCOUNT_ID
    sync: true
  - key: API_KEY
    sync: true
  - key: TELEGRAM_USER
    sync: true
  - key: APP_URL
    sync: true
  - key: TOKEN
    sync: true
  - key: PYTHON_VERSION
    sync: true
  - fromGroup: Environment-Signal-Copier-Telegram-Bot
  region: frankfurt
  buildCommand: pip install -r requirements.txt
  startCommand: python run.py
version: "1"
